### DISCUSSION TITLE
How to implement horizontal scaling with docker?

### DISCUSSION THREAD

**Discussion by TheMetaverseEngineer** [colyseus/colyseus#714] [Q&A]
hi. this is my game server docker compose service:

```yaml
game-server:
    build:
      context: .
      dockerfile: ./apps/game_server/Dockerfile
    deploy:
      replicas: 4
```

I'm using the same domain for all 4 containers and using nginx as a load balancer to distribute requests between them but I'm getting the `seat reservation expired` error.  I want to know if I must use different domains for each container or I can make it work with a single domain and a load balancer?
